-- TCL (TRANSACTION CONTROL LANGUAGE) 
-- COMMIT ROLLBACK SAVEPOINT

-- 데이터 변경 사항을 묶어 하나의 트랜젝션에 적용

-- SAVEPOINT NAME;

-- SAVEPOINT NAME2;

-- ROLLBACK TO NAME;

SELECT * FROM DEPARTMENT2;
INSERT INTO DEPARTMENT2 (DEPT_ID,DEPT_TITLE,LOCATION_ID)
VALUES ('D0','경리부','L2');

COMMIT;
ROLLBACK;

DELETE FROM DEPARTMENT2
WHERE DEPT_ID = 'D0';

SAVEPOINT SP1;

SELECT * FROM DEPARTMENT2;

DELETE FROM DEPARTMENT2
WHERE DEPT_ID = 'D9';

ROLLBACK TO SP1;

