select username from dba_users;
--ctrl + enter 

ALTER SESSION SET "_ORACLE_SCRIPT" = TRUE; /**/

CREATE USER ldh IDENTIFIED BY ldh1234;

GRANT CONNECT, RESOURCE TO ldh;

ALTER USER ldh DEFAULT TABLESPACE SYSTEM QUOTA UNLIMITED ON SYSTEM;