CREATE USER ldh_member IDENTIFIED BY member1234;

GRANT CONNECT,RESOURCE,CREATE VIEW TO ldh_member;
ALTER USER ldh_member DEFAULT TABLESPACE SYSTEM QUOTA UNLIMITED ON SYSTEM;
GRANT CREATE TABLE TO ldh_member;
REVOKE CREATE TABLE FROM ldh_member;

CREATE TABLE MEMBER(
    MEMBER_NO NUMBER CONSTRAINT PK_MEMBER_NO PRIMARY KEY,
    MEMBER_ID VARCHAR2(20),
    MEMBER_PW VARCHAR2(20) NOT NULL,
    MEMBER_NM VARCHAR2(20),
    MEMBER_GENDER CHAR(1) CONSTRAINT CHK_MEMBER_GENDER CHECK (MEMBER_GENDER IN('M','F')),
    ENROLL_DATE DATE DEFAULT SYSDATE,
-- ENROLL 등록하다.
    SECESSION_FL CHAR(1) DEFAULT 'N' CONSTRAINT CHK_SECE_FL CHECK(SECESSION_FL IN ('Y','N'))
-- 탈퇴여부 
);
ALTER TABLE MEMBER RENAME CONSTRAINT SYS_C008431 TO NN_MB_PW;
SELECT * FROM ALL_CONSTRAINTS
WHERE TABLE_NAME = 'MEMBER';

COMMENT ON COLUMN MEMBER.MEMBER_NO IS '회원 번호';
COMMENT ON COLUMN MEMBER.MEMBER_ID IS '아이디';
COMMENT ON COLUMN MEMBER.MEMBER_PW IS '비밀 번호';
COMMENT ON COLUMN MEMBER.MEMBER_NM IS '회원 이름';
COMMENT ON COLUMN MEMBER.MEMBER_GENDER IS '성별';
COMMENT ON COLUMN MEMBER.ENROLL_DATE IS '가입 일자';
COMMENT ON COLUMN MEMBER.SECESSION_FL IS '탈퇴 여부';

CREATE TABLE BOARD (
    BOARD_NO NUMBER CONSTRAINT PK_BOARD_NO PRIMARY KEY,
    BOARD_TITLE VARCHAR2(200) CONSTRAINT NN_BOARD_TITLE NOT NULL,
    BOARD_CONTENT VARCHAR2(4000) CONSTRAINT NN_BOARD_CONTENT NOT NULL,
    CREATE_DATE DATE DEFAULT SYSDATE,
    READ_COUNT NUMBER DEFAULT 0,
    CREATE_MEMBER_NO NUMBER CONSTRAINT FK_MEMBER_NO REFERENCES MEMBER(MEMBER_NO) 
);
ALTER TABLE BOARD RENAME COLUMN CREATE_MEMBER_NO TO MEMBER_NO;

ALTER TABLE BOARD RENAME CONSTRAINT FK_MEMBER_NO TO FK_BOARD_MBNO;
SELECT * FROM ALL_CONSTRAINTS
WHERE TABLE_NAME = 'BOARD';

COMMENT ON COLUMN BOARD.BOARD_NO IS '게시글 번호';
COMMENT ON COLUMN BOARD.BOARD_TITLE IS '게시글 제목';
COMMENT ON COLUMN BOARD.BOARD_CONTENT IS '게시글 내용';
COMMENT ON COLUMN BOARD.CREATE_DATE IS '게시글 작성일';
COMMENT ON COLUMN BOARD.READ_COUNT IS '조회수';
COMMENT ON COLUMN BOARD.CREATE_MEMBER_NO IS '회원 작성자 NO';

CREATE TABLE REPLY(
    REPLY_NO NUMBER CONSTRAINT PK_REPLY_NO PRIMARY KEY,
    REPLY_CONTENT VARCHAR2(500) CONSTRAINT NN_REPLY_CONT NOT NULL,
    CREATE_DATE DATE DEFAULT SYSDATE,
    REPLY_MEMBER_NO NUMBER CONSTRAINT FK_REPLY_MBNO REFERENCES MEMBER(MEMBER_NO),
    BOARD_NO NUMBER CONSTRAINT FK_REPLY_BDNO REFERENCES BOARD(BOARD_NO)
);
SELECT * FROM ALL_CONSTRAINTS
WHERE TABLE_NAME = 'REPLY';

COMMENT ON COLUMN reply.reply_no IS '댓글 번호';
COMMENT ON COLUMN reply.reply_content IS '댓글 내용';
COMMENT ON COLUMN REPLY.CREATE_DATE IS '댓글 작성일';
COMMENT ON COLUMN REPLY.REPLY_MEMBER_NO IS '댓글 작성자';
COMMENT ON COLUMN REPLY.BOARD_NO IS '게시글 번호';

CREATE SEQUENCE SEQ_MEMBER_NO;
CREATE SEQUENCE SEQ_BOARD_NO;
CREATE SEQUENCE SEQ_REPLY_NO;

--------------------------------------------------------------------------------
SELECT COUNT(*) FROM MEMBER
WHERE MEMBER_ID = ''
AND SECESSION_FL = 'N';

select * from all_CONSTRAINTS
where table_name = 'MEMBER';

UPDATE MEMBER 
SET MEMBER_NM = '임동현' , MEMBER_GENDER = 'F'
WHERE MEMBER_NO = 1;

rollback;

SELECT MEMBER_PW
FROM MEMBER
WHERE MEMBER_NO = '1'
AND MEMBER_PW = 'asfd';

SELECT * FROM ALL_CONSTRAINTS
WHERE TABLE_NAME = 'MEMBER';